name = "iga-milk-lactalis-proxy"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
LACTALIS_BASE = "https://mylactalis.com.au"
SLOT_CONFIG_ID = "869"

[[kv_namespaces]]
binding = "SESSIONS"
id = "2e9fb21f3e6a409e96922f7f02cfdfcd"
